### ISSUE TITLE
Demo site rendering issue with FireFox and Firefox Developer 

### ISSUE THREAD

**Issue by rbfii** [Jonnyauk/Wonderflux#45]
The Demo site http://wonderflux.com/demo-girder/ renders strangely on Firefox

The header is 24153.5 px height
![wonderflux1](https://cloud.githubusercontent.com/assets/11374145/8027777/3729423e-0d53-11e5-8436-a01df55fab7a.jpg)

**Comment by Jonnyauk** [comment]
Hi Rob,
thanks for the feedback... in all honesty I've not tested Girder in Firefox! 

That's weird - let me take a look into that when I get a chance this week (very busy with project work at the mo!)

**Comment by wimstefan** [comment]
It seems to be related to the box-sizing settings in wf-css-flux-layout-core.css - as soon as I disable it in my Developer console the relations are normal again ...

But that's just a guess since I started to use wonderflux only by today and noticed the same issue and was just playing around a bit without really knowing what I do since I'm not just a simple Wordpress user looking into the possibility of using a framework ....

**Comment by Jonnyauk** [comment]
Great - thank you for the diagnosis - I appreciate it!

This sounds like quite a major rendering bug - I've completely changed the CSS layout generation engine in Wonderflux v2 and clearly need to do some more testing (my initial testing was with very basic layouts). I've had a quick peek in Firefox now, whooa, spacing is all out - strange, because when I quickly viewed some other Wonderflux v2 sites such as http://jonnya.net and http://wonderflux.com they are fine!?

I'm absolutely stacked out with project work right now (which is what pays the bills ;) but will try and take a look over the weekend if I get a chance. I feel as the other sites render perfectly there is something else weird going on - I have a bit of an unusual WordPress multisite + CDN setup on wonderflux.com so that could possibly be bumping a file somewhere.

**Comment by Blarkdackbyte** [comment]
Hi!
I have a similar issue!
In Firefox i have to scroll a lot to get to the content.
I find out, that it has something todo with the "box-sizing: inherit".
In Chrome the demopage works perfectly.
If i insert a simple "<div></div>" between the search textfield and the button, the page is shown correctly.


![firefoxrenderissue](https://cloud.githubusercontent.com/assets/14968844/10270676/c50234a4-6af9-11e5-82ac-b9dc3ca8c9bd.png)

**Comment by rbfii** [comment]
If you wish to have further testing on the cross browser usability I am available as I am currently hunting for a new place to continue my career.

**Comment by Jonnyauk** [comment]
Thanks guys - mega busy at the moment with client work but will look into this when I get a chance...very strange!

**Comment by AGSoftAU** [comment]
Issue is caused due to line-height set on the submit. No adverse effects displayed from removing it.

An ideal world I would prefer to omit the submit button text altogether and set it via aria-label instead. Sadly due to the doctype this isn't possible.

**Comment by Jonnyauk** [comment]
Awesome - thank you so much AG, it's appreciated! I'm just so stacked out with project work (and a little stressed too!) thanks!!
