### ISSUE TITLE
Page Templates and Post Types

### ISSUE THREAD

**Issue by tech4him1** [Jonnyauk/Wonderflux#57]
What is the best way to create a custom page template and/or post type in a child theme?

**Comment by Jonnyauk** [comment]
Hi! The best way to create a page template is to just duplicate page.php from the Wonderflux directory into your child theme directory (keep all hooks intact!) - and then put this at the top of the file (as normal with a WordPress custom page template):

    <?php
    /**
     * Template Name: My custom template name
     */
    ?>

Regarding post types - that is made much simpler for you with Wonderflux because of the way it extends `get_template_part()` with the Wonderflulx function `wfx_get_template_part()`, you can use the following `loop-content` files in your child theme:

- `loop-content-single-{post-type-slug}.php` (single custom post type view loop content)
- `loop-content-archive-{post-type-slug}.php` (custom post type archive view loop content)

You can read more about this in the documentation (Extend template parts with location awareness section in `readme.md` file - also shown on https://github.com/Jonnyauk/Wonderflux)

**Comment by tech4him1** [comment]
Thank You

**Comment by Jonnyauk** [comment]
No probs - hope that helps ;)

**Comment by tech4him1** [comment]
Could I also do something similar to page-templates/page-template-no-sidebar.php like:
```php
<?php
/**
 * Template Name: My custom template name
 */
get_template_part('page');
?>
```
Then in loop-content.php, something like:
```php
if( is_page_template('My custom template name') ) {
     \\ Do something
}
```

**Comment by Jonnyauk** [comment]
Regarding the first question - no you can't - this is including the whole page.php file from Wonderflux. You'd be best creating a separate, new page template by duplicating page.php into your child theme directory.

Regarding your second question - sure - you could certainly do that - but it might be best to use `loop-content-page.php` template part here and then detect inside that using the function `is_page_template()` as you've done in your example (but if you have no `loop-content-page.php` file in your child theme, sure, it will also work in `loop-content.php` just fine ;)

**Comment by tech4him1** [comment]
OK, thanks for taking the time to explain it to me.  I am not sure that I completely understand why to duplicate instead of include, but if that is best, I will definitely do it that way.  The only reason I was thinking of including is because then, if the hooks ever changed, they would be imported into my template that way.

**Comment by Jonnyauk** [comment]
No probs - I don't get many support requests and have a light day of work today!

Basically, you'd duplicate, rather than include because you'd not be able to work inside the page template if you just included page.php (as per example).

**You may find that the hooks are of use** instead of creating a completely separate page template - I rarely have to create separate page templates these days.

Good point on the hooks - but honestly the page hooks have not changed for a few years and I don't envisage changing them any time soon - I've found no limitations with the current hooks deployed throughout Wonderflux in a long time - and I don't want to go breaking my sites (or other peoples like yours ;)

**Comment by tech4him1** [comment]
Is there any way to just make a page template show up in the list, and then just modify it with hooks?

**Comment by Jonnyauk** [comment]
I'm not sure that WordPress can do that (you can certainly remove a page template, but not 100% sure how you make a 'fake' page template appear in the menu)

If you are looking to build out custom page content we use Advanced Custom Fields quite a bit - it's very powerful (check out the paid for version with Flexible Content - really cool - you can build a cmplete page builder system, hence why we don't really use page templates anymore!)

**Comment by tech4him1** [comment]
Great, thanks for the info.  Custom fields were actually the reason I was looking to make a page template, but Advanced Custom Fields looks better.

**Comment by Jonnyauk** [comment]
If you are populating a page layout with custom fields (ACF or otherwise), we just insert the custom field content within a function attached to a Wonderflux hook - let me know if you find limitations with this, I'm always open to feedback and potential code improvements ;)

One big tip to identify Wonderflux hooks is to set a constant in your child theme functions.php file:

`define( 'WF_DEBUG', true );`

This will reveal all the hooks available in your current view (if you are logged-in to WordPress as an admin level user).

Another way would be to create a loop-content-page.php file, and then you are fee to intermingle your custom field data output within the actual page content. Incidentally - I've deliberately not put hooks into the loop-content (or other -content) template parts to keep the files cleaner and not introduce issues with Wonderflux upgrades in the future.

**Comment by tech4him1** [comment]
That definitely makes sense not to put hooks in loop-content pages.  The only problem with that that I am seeing (unless I am missing something) is that you can't get content inside the actual "post" div with a hook. I wonder if a hook in the `while ( have_posts() ) : the_post();` loop would work, you could then use that to set the "post" div settings (similar to 'wflux_layout_content_container_open' and 'wflux_layout_content_container_close').

Thanks for the info on WF_DEBUG, that will be helpful.  I have been trying ACF and I think it will do exactly what I was looking for.  Do you know if you can get ACF fields by group, instead of individually? I didn't see that anywhere in the ACF docs.

**Comment by tech4him1** [comment]
Also, what method do you use to make sure ACF hooks/functions do not fail when it is not installed?

**Comment by Jonnyauk** [comment]
Regarding hooks - yes, there are none available actually inside the loop (for the previous mentioned reasons), so I'd suggest building your own `loop-content-page.php` file. There would also be nothing stopping you creating your own hooks inside this file too if you need them, but I don't want to put any hooks actually inside any of the `loop-content` template parts for the reasons mentioned previously.

However, if you take a look at `loop.php`you will see that there are some hooks to get inside the content area - `WF_DEBUG` constant is the best way to see the position of these in relation to your actual page output.

We basically only work on bespoke themes for clients using Wonderflux and don't build/distribute themes for other people to use - so we don't need to worry about not having ACF installed.

You could try something like this:
`
<?php 
     if( class_exists('acf') ) {
        //do stuff
     }
?>
`

**Comment by tech4him1** [comment]
Thanks!
