### ISSUE TITLE
RSS Feed & Other

### ISSUE THREAD

**Issue by Dharator** [Jonnyauk/Wonderflux#58]
I'm creating a new theme and before i start i want to solve an issue i'm having with the RSS Feed, it doesn't display posts (in a local install it shows me Call to a member function filter_post_class() on a non-object in D:\xampp\htdocs\wordpress\wp-content\themes\wonderflux\functions.php on line 872 and in a live site it looks the same as your girder, incomplete), the other issue is in the wp-admin on WFX System info, it tells me that i'm using a development version, i installed the 2.3 and even tried the 2.2 and still says the same.

**Comment by Jonnyauk** [comment]
Hi @Dharator - thanks for your feedback!

Regarding your first point about RSS - I'm struggling to replicate this - do you have any other plugins installed? Please can you de-activate all plugins and test again and let me know. The RSS feeds are working on both wonderflux.com and other sites that I have live?

Regarding your second point - it sounds like you have downloaded straight from the master development branch, rather than from the releases page - however, I'll test this just to make sure.

Let me know your thoughts - and thanks for leaving feedback, I really do appreciate it and want to help you work through these issues for everyones benefit ;)

**Comment by Dharator** [comment]
I have no plugins installed, it's just a fresh install, when i said that the feed of girder didn't worked i meant your demo as well (http://wonderflux.com/demo-girder/feed/), it doesn't show any posts, with the second point i downloaded it from the releases page (https://github.com/Jonnyauk/Wonderflux/releases/tag/2.3)

**Comment by Jonnyauk** [comment]
Thanks for responding - I'll certainly take a look into this ;)

**Comment by Jonnyauk** [comment]
I've just done a fresh install of WordPress 4.6, no plugins with Wonderflux v2.3 (from release page). I also used the import data from https://wpcom-themes.svn.automattic.com/demo/theme-unit-test-data.xml - the feed does seem to work. I will check deeper into this just to make sure though over the next few days when I get a chance.

Why you are not seeing it on the Girder demo is that there are no posts in the site - so therefore there is no data to populate into the RSS feed (it only has 'pages'). However, as I said, I'll look into this further just to be sure ;)

RE second point (version check) - thank you for flagging this up - I have replicated this on my local test install and indeed it is reporting 'development version' incorrectly - thanks for spotting this, I'll look into this and roll out a bug fix ;)

**Comment by Dharator** [comment]
Hey, thanks for looking into it, as a side note your girder demo does have a post (http://wonderflux.com/demo-girder/2015/03/17/hello-world/), and if you look at your rss you'll notice that the <rss> and <channel> have no closing tags, like the feed just stopped displaying the information.

**Comment by Jonnyauk** [comment]
@Dharator - good spot - that's weird as it worked on my fresh local install... I'll certainly look into that deeper!

RE version check, I've had a quick look (at this very old code!) and noticed that it's fetching the data from an old Feedburner account I had (which is now not updating any more) so that should be pretty easy to fix - great spot (as I always run the development versions of Wonderflux on live sites so I'm used to seeing it!)

**Comment by Jonnyauk** [comment]
OK, got the feed fixed - good spot!

I'll move onto the version/update checker over the weekend. In the meantime, if you are desperate for RSS feeds, download straight from the master branch on GitHub and rename the directory to 'wonderflux' (I'll hope to push out a new release by Monday if you can wait!)

**Comment by Dharator** [comment]
Great! thank you.

**Comment by Jonnyauk** [comment]
Just release Wonderflux version 2.4, this should fix the issues reported. Thanks again for reporting, if you spot anything else (or have ideas for improvements) just let me know ;)
